/**
 * @fileoverview Stable string error codes returned in error responses. Host apps
 * and clients pattern-match on these — they MUST NOT change between minor
 * versions. `as const` preserves the literal types in the emitted `.d.ts`.
 * @layer shared/constants
 */
export const STORAGE_ERROR_CODES = {
  STORAGE_NOT_CONFIGURED: 'STORAGE_NOT_CONFIGURED',
  STORAGE_KEY_INVALID: 'STORAGE_KEY_INVALID',
  STORAGE_BODY_MISSING: 'STORAGE_BODY_MISSING',
  STORAGE_CONTENT_TYPE_REQUIRED: 'STORAGE_CONTENT_TYPE_REQUIRED',
  STORAGE_MIME_NOT_ALLOWED: 'STORAGE_MIME_NOT_ALLOWED',
  STORAGE_SIZE_EXCEEDED: 'STORAGE_SIZE_EXCEEDED',
  STORAGE_VALIDATION_FAILED: 'STORAGE_VALIDATION_FAILED',
  STORAGE_SCAN_INFECTED: 'STORAGE_SCAN_INFECTED',
  STORAGE_SCAN_INCONCLUSIVE: 'STORAGE_SCAN_INCONCLUSIVE',
  STORAGE_OBJECT_NOT_FOUND: 'STORAGE_OBJECT_NOT_FOUND',
  STORAGE_PROVIDER_ERROR: 'STORAGE_PROVIDER_ERROR',
  STORAGE_SIGNED_URL_TTL_INVALID: 'STORAGE_SIGNED_URL_TTL_INVALID',
  STORAGE_PART_TOO_SMALL: 'STORAGE_PART_TOO_SMALL',
  STORAGE_BUCKET_UNDEFINED: 'STORAGE_BUCKET_UNDEFINED',
  STORAGE_MULTIPART_ABORTED: 'STORAGE_MULTIPART_ABORTED',
  STORAGE_INVALID_CONFIG: 'STORAGE_INVALID_CONFIG',
  STORAGE_TIMEOUT: 'STORAGE_TIMEOUT',
} as const

/** Union of every stable storage error code. */
export type StorageErrorCode = (typeof STORAGE_ERROR_CODES)[keyof typeof STORAGE_ERROR_CODES]
