/**
 * @fileoverview HTTP status per storage error code. `StorageException` derives
 * its default status from this map. Internal — not exported from the barrel.
 * @layer server/errors
 */
import { HttpStatus } from '@nestjs/common'
import {
  STORAGE_ERROR_CODES,
  type StorageErrorCode,
} from '../../shared/constants/error-codes.constants'

/**
 * Status per error code. `Record<StorageErrorCode, HttpStatus>` forces
 * exhaustiveness at compile time.
 */
export const STORAGE_ERROR_STATUS: Record<StorageErrorCode, HttpStatus> = {
  [STORAGE_ERROR_CODES.STORAGE_NOT_CONFIGURED]: HttpStatus.SERVICE_UNAVAILABLE,
  [STORAGE_ERROR_CODES.STORAGE_KEY_INVALID]: HttpStatus.BAD_REQUEST,
  [STORAGE_ERROR_CODES.STORAGE_BODY_MISSING]: HttpStatus.BAD_REQUEST,
  [STORAGE_ERROR_CODES.STORAGE_CONTENT_TYPE_REQUIRED]: HttpStatus.BAD_REQUEST,
  [STORAGE_ERROR_CODES.STORAGE_MIME_NOT_ALLOWED]: HttpStatus.UNSUPPORTED_MEDIA_TYPE,
  [STORAGE_ERROR_CODES.STORAGE_SIZE_EXCEEDED]: HttpStatus.PAYLOAD_TOO_LARGE,
  [STORAGE_ERROR_CODES.STORAGE_VALIDATION_FAILED]: HttpStatus.BAD_REQUEST,
  [STORAGE_ERROR_CODES.STORAGE_SCAN_INFECTED]: HttpStatus.UNPROCESSABLE_ENTITY,
  [STORAGE_ERROR_CODES.STORAGE_SCAN_INCONCLUSIVE]: HttpStatus.UNPROCESSABLE_ENTITY,
  [STORAGE_ERROR_CODES.STORAGE_OBJECT_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [STORAGE_ERROR_CODES.STORAGE_PROVIDER_ERROR]: HttpStatus.BAD_GATEWAY,
  [STORAGE_ERROR_CODES.STORAGE_SIGNED_URL_TTL_INVALID]: HttpStatus.BAD_REQUEST,
  [STORAGE_ERROR_CODES.STORAGE_PART_TOO_SMALL]: HttpStatus.BAD_REQUEST,
  [STORAGE_ERROR_CODES.STORAGE_INVALID_PART_COUNT]: HttpStatus.BAD_REQUEST,
  [STORAGE_ERROR_CODES.STORAGE_BUCKET_UNDEFINED]: HttpStatus.BAD_REQUEST,
  [STORAGE_ERROR_CODES.STORAGE_MULTIPART_ABORTED]: HttpStatus.INTERNAL_SERVER_ERROR,
  [STORAGE_ERROR_CODES.STORAGE_INVALID_CONFIG]: HttpStatus.INTERNAL_SERVER_ERROR,
  [STORAGE_ERROR_CODES.STORAGE_TIMEOUT]: HttpStatus.GATEWAY_TIMEOUT,
}
